// uploadToEtsy.js
import fetch from 'node-fetch';
import dotenv from 'dotenv';
dotenv.config();

const shopId = process.env.ETSY_SHOP_ID;
const accessToken = process.env.ETSY_ACCESS_TOKEN;

const createListing = async () => {
  const url = `https://api.etsy.com/v3/application/shops/${shopId}/listings`;

  const listingData = {
    title: "AI Designed T-Shirt – Abstract Lines",
    description: "This unique T-shirt design is generated by an AI trained on abstract art patterns. Perfect for minimalists and design lovers.",
    price: 19.99,
    quantity: 10,
    taxonomy_id: 1032, // örnek kategori: Clothing > Unisex Adult T-shirts
    tags: ["AI", "tshirt", "abstract", "minimal", "art"],
    type: "physical",
    who_made: "i_did",
    is_supply: false,
    when_made: "made_to_order",
  };

  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
        'Accept': 'application/json',
      },
      body: JSON.stringify(listingData)
    });

    const data = await response.json();

    if (!response.ok) {
      console.error("Hata oluştu:", data);
    } else {
      console.log("Başarıyla yüklendi:", data);
    }
  } catch (error) {
    console.error("İstek sırasında hata:", error);
  }
};

createListing();
