name: Upload Generated Image to Supabase

on:
  workflow_dispatch:

jobs:
  upload-image:
    runs-on: ubuntu-latest

    steps:
      - name: Repo klonla
        uses: actions/checkout@v3

      - name: Node.js ortamı kur
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Paketleri kur
        run: npm install

      - name: Çevresel değişkenleri yükle
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env

      - name: Supabase’e görsel yükle
        run: node uploadToSupabase.js
