name: Printify Ürün Yükleme

on:
  workflow_dispatch:  # Elle çalıştırmak için

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Repo’yu çek
        uses: actions/checkout@v2

      - name: Node.js kur
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Paketleri kur
        run: npm install

      - name: Printify’ye yükle
        env:
          PRINTIFY_API_KEY: ${{ secrets.PRINTIFY_API_KEY }}
        run: node uploadToPrintify.js
